### ISSUE TITLE
Getting "Error: Naming collision detected" On npm start

### ISSUE THREAD

**Issue by simonburns** [KelseyRegan/react-native-qrcode-view#1]
Error is as follows:

![screen shot 2016-02-16 at 2 58 21 am](https://cloud.githubusercontent.com/assets/8815400/13074402/31b1f8a0-d459-11e5-952d-eb34c611792c.png)
Error: Naming collision detected: /Users/simonburns/Dev/ReactNativeCasts/authentication/node_modules/react-native-qrcode-view/node_modules/react-native/Libraries/vendor/react/vendor/core/ExecutionEnvironment.ios.js collides with /Users/simonburns/Dev/ReactNativeCasts/authentication/node_modules/react-native/Libraries/vendor/react/vendor/core/ExecutionEnvironment.ios.js

**Comment by getreup** [comment]
Hey @simonburns,
Can you try removing the directory:

/Users/simonburns/Dev/ReactNativeCasts/authentication/node_modules/react-native-qrcode-view/node_modules

**Comment by BigPun86** [comment]
+1 Removing the node_modules folder fixed it for me

**Comment by simonburns** [comment]
Ah got it - thanks @BigPun86, appreciate it.
